server:
  port: 8083
mybatis:
  mapper-locations: classpath:com/qf/mapper/*.xml
  type-aliases-package: com.qf.exam.pojo
#  configuration: map-underscore-to-camel-case:true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-bp1qqfg22ytzyvwdzjo.mysql.rds.aliyuncs.com:3306/exam?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Llp19950705
  thymeleaf:
    cache: false